title: da-course-builder
tagline: A brand new course on Learning Lab
description: test out
template:
  repo: da-course-builder-template
  name: da-course-builder
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
